# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/DinoColling/GPS_V2.0/GPS_V2.0.srcs/sources_1/ip/FIR_Filter/FIR_Filter.xci
# IP: The module: 'FIR_Filter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DinoColling/GPS_V2.0/GPS_V2.0.gen/sources_1/ip/FIR_Filter/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_Filter'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DinoColling/GPS_V2.0/GPS_V2.0.gen/sources_1/ip/FIR_Filter/FIR_Filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_Filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/DinoColling/GPS_V2.0/GPS_V2.0.srcs/sources_1/ip/FIR_Filter/FIR_Filter.xci
# IP: The module: 'FIR_Filter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DinoColling/GPS_V2.0/GPS_V2.0.gen/sources_1/ip/FIR_Filter/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_Filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DinoColling/GPS_V2.0/GPS_V2.0.gen/sources_1/ip/FIR_Filter/FIR_Filter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_Filter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
