# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/design.xdc

# IP: ip/DDS_Gen/DDS_Gen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DDS_Gen || ORIG_REF_NAME==DDS_Gen} -quiet] -quiet
