# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/DinoColling/GPS_V2.0/GPS_V2.0.srcs/sources_1/ip/fifo_gps_data/fifo_gps_data.xci
# IP: The module: 'fifo_gps_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DinoColling/GPS_V2.0/GPS_V2.0.gen/sources_1/ip/fifo_gps_data/fifo_gps_data.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gps_data'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DinoColling/GPS_V2.0/GPS_V2.0.gen/sources_1/ip/fifo_gps_data/fifo_gps_data_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gps_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DinoColling/GPS_V2.0/GPS_V2.0.gen/sources_1/ip/fifo_gps_data/fifo_gps_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gps_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/DinoColling/GPS_V2.0/GPS_V2.0.srcs/sources_1/ip/fifo_gps_data/fifo_gps_data.xci
# IP: The module: 'fifo_gps_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DinoColling/GPS_V2.0/GPS_V2.0.gen/sources_1/ip/fifo_gps_data/fifo_gps_data.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gps_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DinoColling/GPS_V2.0/GPS_V2.0.gen/sources_1/ip/fifo_gps_data/fifo_gps_data_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gps_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/DinoColling/GPS_V2.0/GPS_V2.0.gen/sources_1/ip/fifo_gps_data/fifo_gps_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_gps_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
